### ISSUE TITLE
how to change addon's order priority?

### ISSUE THREAD

**Issue by hjsg1010** [CDub619/flyPlateBuffs#3]
Hi, really thanks for edit useful addons by alone.
I really appreciate it.

However, can I change order priority?
I am using 'plater' nameplate addons, but the plater keep covering fpb buffs. (below figure)
![캡처](https://user-images.githubusercontent.com/17421673/205832571-76c03255-07dc-449b-9a23-a5d1e6c81bfb.PNG)

I want to fbp buffs priority is the first, so other interface doesn't cover it. 

I changed the plater nameplate priority to 'background' or 'low' but it doesn't work :(

sorry for my poor English skills.

Have a nice day.

**Comment by Bambiiqt** [comment]
Currently fpb only attaches correctly to the default blizzard frames and ThreatPlates, when I release later as flyerPlateBuffs it will attach to Plater , Neat Plates and Tidy Plates

**Comment by hjsg1010** [comment]
> fault blizzard frames and ThreatPlates, when I release later as flyerPlateBuffs it will attach to Plater , Neat Plates and Tidy Plates

Oh, Thanks, I will keep following your repo.
Also, I will support your work by paypal (https://www.curseforge.com/wow/addons/easycc) Thx!!

**Comment by Bambiiqt** [comment]
I had a moment today and I think  I fixed it for proper snapping to Plater Plates, check it out and let me know

**Comment by hjsg1010** [comment]
> I had a moment today and I think I fixed it for proper snapping to Plater Plates, check it out and let me know

Sorry for late response, It works! Thx a lot!

**Comment by bellid8** [comment]
Hello! I just noticed that the personal resource display ( the buffs on the HP bar below your character ) aren't being displayed if the addon is enabled. I am using defaults plates, unitframes, etc. Btw, Thanks a lot for your work.
